# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c639ec018af70a1c06b19ae97593a13564ec4d6eaf19932f9f25428b8b2dbb7434a4f9d8bde3d26a3a6d023fe545224e0ca059380ecc7cf3f28029ca3d856ca

test:
  secret_key_base: 6fde6fb947ba358097625a1de556d57f9993f804a966f3cb234bd606d599830f69e0310851ffff4e606002819ae8273cbdde3ffeb32c3351549e3158031b3f24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
